# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r0hBCZFR7VwqR8p4-V5pOVmZNN24Oxpf
"""

import seaborn as sns
import pandas as pd

df= pd.read_csv("/content/movies.csv")

from ydata_profiling import profile_report
profile = ProfileReport(df)
profile.to_file("output.html")



